Script improvements around versioning and combinations + more

diff --git a/lion_torches b/lion_torches
--- a/lion_torches
+++ b/lion_torches
@@ -1,9 +1,8 @@
 #!/bin/sh
 # =======================================================================
-# This script unforms Vaultron
-#
-# CAUTION: This removes all Vault data and Terraform state!
-# Use `terraform destroy` instead if you wish to selectively preserve data.
+# This script is the nuclear option; it removes all traces of Vaultron
+# created data so that the user can start over. It does not invoke
+# Terraform and instead uses OS and docker commands only
 #
 # shellcheck disable=SC1091
 # =======================================================================
@@ -11,25 +10,17 @@
 . ./skydome
 
 # Preflight checks
-if [ -z "$(command -v terraform)" ]; then
-  msg alert "Vaultron cannot unform! Could not locate terraform command."
-  msg info "Get Terraform from: https://www.terraform.io/downloads.html"
-  exit 1
-fi
-
 check_flavor
+
+TF_VAR_vault_flavor=$TF_VAR_vault_flavor || TF_VAR_vault_flavor=consul
 
 check_docker
 
-msg greeting "Unform Vaultron ..."
+msg greeting "Lion Torches removing all Vaultron generated data ..."
 
-cd "flavors/$TF_VAR_vault_flavor" || exit 1
+cd "flavors/$TF_VAR_vault_flavor" || echo "Cannot select flavor" && exit 1
 
-if ! destroy; then
-  msg alert "Terraform destroy failed, infrastructure may still exist."
-  msg info "You can manually clean up Vaultron with lion_torches."
-fi
-
+if ! docker stop vaultron-vault
 # If we cannot write to the Consul data, alert user and attempt to change
 # ownership of consul/vault folders to avoid failure with Terraform destroy
 # NB: This occurs on Docker on Linux but not Docker for Mac
@@ -83,13 +74,6 @@ errors=$((errors + $?))
 rm -f ./vault/vault_DEV_ONLY*.tmp
 errors=$((errors + $?))
 
-if [ "$TF_VAR_vault_flavor" = "raft" ]; then
-  rm -rf ./vault/vault3
-  errors=$((errors + $?))
-  rm -rf ./vault/vault4
-  errors=$((errors + $?))
-fi
-
 # Remove Telemetry data
 rm -rf ./yellow_lion/grafana_data
 errors=$((errors + $?))
@@ -108,7 +92,6 @@ errors=$((errors + $?))
 
 if [ $errors -gt 0 ]; then
   msg alert "Vaultron unformed (with $errors errors)!"
-  msg info "You can manually clean up Vaultron with lion_torches."
   tput sgr0
 else
   msg boom "Vaultron unformed!"
